"""jevex: extract typed records from web pages and PDFs using Jev."""

from jevex._pdfium import UnreadablePdfError
from jevex.baseline import (
    Baseline,
    BaselineError,
    Check,
    GateResult,
    GateTolerances,
    check_baseline,
    corpus_digest,
    ensure_comparable,
)
from jevex.benchmarks import (
    BenchmarkConfig,
    BenchmarkConfigError,
    BookPageError,
    BootstrapSettings,
    CorpusLock,
    CorpusLockError,
    CorpusSpec,
    Interval,
    LockCheck,
    PinnedModel,
    PinnedModels,
    book_values,
    books_corpus,
    bootstrap_interval,
    check_lock,
    lock_corpus,
    verify_lock,
)
from jevex.budgets import BudgetEvent, Budgets, DocBudget, DocumentBudget, RunBudget, RunLedger
from jevex.categorise import CategoriseStage, JevStatementClassifier, ToClassify
from jevex.clean import BoilerplateCleaner, CleanStage
from jevex.component_gate import ComponentGateStage, GateUnit, NoulComponentGate, gate_units
from jevex.document import Document
from jevex.entities import EntityScope
from jevex.eval import EvalReport, Tolerance, evaluate, load_corpus
from jevex.extractor import ExtractionResult, Extractor, document_stat
from jevex.fallback import FallbackStage, LLMFieldExtractor
from jevex.fetch import FetchError, RobotsDisallowedError, SimpleFetcher
from jevex.gate import (
    DefaultTextReader,
    DocumentGateStage,
    DocumentText,
    HtmlTextReader,
    NoulDocumentGate,
    PdfTextReader,
    TextReader,
)
from jevex.generators import (
    GeneratorRegistry,
    GeneratorSpec,
    InvalidGeneratorError,
    MatchSpec,
    Provenance,
    RegexGenerator,
    SpecScope,
    default_registry,
    generator_spec_json_schema,
)
from jevex.housekeeping import DuplicateGenerator, GeneratorUse, Housekeeper, generator_use
from jevex.images import (
    DefaultImageLoader,
    ImageData,
    ImageLoader,
    ImageReading,
    ImageStage,
    ImageText,
    OcrEngine,
    OcrProcessor,
    RapidOcrEngine,
    UnreadableImageError,
    text_components,
)
from jevex.interfaces import LLMAnswer
from jevex.keypaths import (
    FlatBlob,
    KeyPathMapper,
    Leaf,
    StructuredMode,
    StructuredResult,
    StructuredStage,
    flatten,
)
from jevex.layout import (
    BBox,
    Component,
    ComponentType,
    DomLocation,
    ImageLocation,
    LayoutStage,
    Location,
    PageLocation,
    TableCell,
    UnsupportedDocumentError,
    gated_out_pages,
    section_text,
)
from jevex.layout_html import HtmlLayoutParser
from jevex.layout_pdf import DoclingConverter, PdfLayoutError, PdfLayoutParser
from jevex.learn import (
    ExampleLogger,
    GeneratorLearner,
    GeneratorSnapshot,
    LearnedGenerators,
    LearningSpend,
    LearnMode,
    LearnOutcome,
    LearnStage,
    PackDiff,
    compile_pack,
    example_statement,
)
from jevex.normalise import (
    BUILTIN_NORMALISERS,
    FunctionNormaliser,
    NormaliseError,
    NormaliserRegistry,
    NormaliseStage,
    normalise,
    run_chain,
)
from jevex.packs import (
    ENTRY_POINT_GROUP,
    Changes,
    Pack,
    PackChanges,
    PackError,
    PackManifest,
    community_packs,
    diff_packs,
    export_pack,
    generator_record,
    import_pack,
    layered_generators,
    load_pack,
    pack_generators,
    stored_generators,
)
from jevex.pipeline import Context, Pipeline, Stage
from jevex.replay import LearningStoppedError, ReplayBatch, ReplayReport, replay
from jevex.resolve import (
    ChildFieldError,
    EntityStage,
    InvalidScopeError,
    MultiEntity,
    ParentChild,
    SingleEntity,
)
from jevex.results import Extracted, FieldMeta, Source
from jevex.review import ReviewItem, ReviewQueue, ReviewSink, review_items
from jevex.schema import Field, FieldSpec, Questions, SchemaConfig, SchemaSpec
from jevex.select import CandidateStage, JevCandidateSelector, SelectStage
from jevex.split import DefaultSplitter, DuplicateStatementError, StatementStage, cut_statement
from jevex.statements import (
    Candidate,
    NormaliserStep,
    Span,
    Statement,
    StatementKind,
    TableCellRef,
)
from jevex.stats import Stats, render_page, stats_server
from jevex.store import (
    DocumentEvent,
    DocumentStat,
    GeneratorRecord,
    GeneratorStats,
    KeyMapping,
    SpendEntry,
    SQLiteStore,
    Store,
    StoreError,
    ValueStat,
    VerifiedExample,
    example_id,
    open_store,
)
from jevex.structured import (
    EmbeddedData,
    EmbeddedDataReader,
    SkippedBlob,
    StructuredBlob,
    StructuredSource,
)
from jevex.tables import (
    RowRole,
    blank_rows,
    header_prefix,
    infer_headers,
    row_roles,
    table_statements,
)

__version__ = "0.0.1"

__all__ = [
    "BUILTIN_NORMALISERS",
    "ENTRY_POINT_GROUP",
    "BBox",
    "Baseline",
    "BaselineError",
    "BenchmarkConfig",
    "BenchmarkConfigError",
    "BoilerplateCleaner",
    "BookPageError",
    "BootstrapSettings",
    "BudgetEvent",
    "Budgets",
    "Candidate",
    "CandidateStage",
    "CategoriseStage",
    "Changes",
    "Check",
    "ChildFieldError",
    "CleanStage",
    "Component",
    "ComponentGateStage",
    "ComponentType",
    "Context",
    "CorpusLock",
    "CorpusLockError",
    "CorpusSpec",
    "DefaultImageLoader",
    "DefaultSplitter",
    "DefaultTextReader",
    "DocBudget",
    "DoclingConverter",
    "Document",
    "DocumentBudget",
    "DocumentEvent",
    "DocumentGateStage",
    "DocumentStat",
    "DocumentText",
    "DomLocation",
    "DuplicateGenerator",
    "DuplicateStatementError",
    "EmbeddedData",
    "EmbeddedDataReader",
    "EntityScope",
    "EntityStage",
    "EvalReport",
    "ExampleLogger",
    "Extracted",
    "ExtractionResult",
    "Extractor",
    "FallbackStage",
    "FetchError",
    "Field",
    "FieldMeta",
    "FieldSpec",
    "FlatBlob",
    "FunctionNormaliser",
    "GateResult",
    "GateTolerances",
    "GateUnit",
    "GeneratorLearner",
    "GeneratorRecord",
    "GeneratorRegistry",
    "GeneratorSnapshot",
    "GeneratorSpec",
    "GeneratorStats",
    "GeneratorUse",
    "Housekeeper",
    "HtmlLayoutParser",
    "HtmlTextReader",
    "ImageData",
    "ImageLoader",
    "ImageLocation",
    "ImageReading",
    "ImageStage",
    "ImageText",
    "Interval",
    "InvalidGeneratorError",
    "InvalidScopeError",
    "JevCandidateSelector",
    "JevStatementClassifier",
    "KeyMapping",
    "KeyPathMapper",
    "LLMAnswer",
    "LLMFieldExtractor",
    "LayoutStage",
    "Leaf",
    "LearnMode",
    "LearnOutcome",
    "LearnStage",
    "LearnedGenerators",
    "LearningSpend",
    "LearningStoppedError",
    "Location",
    "LockCheck",
    "MatchSpec",
    "MultiEntity",
    "NormaliseError",
    "NormaliseStage",
    "NormaliserRegistry",
    "NormaliserStep",
    "NoulComponentGate",
    "NoulDocumentGate",
    "OcrEngine",
    "OcrProcessor",
    "Pack",
    "PackChanges",
    "PackDiff",
    "PackError",
    "PackManifest",
    "PageLocation",
    "ParentChild",
    "PdfLayoutError",
    "PdfLayoutParser",
    "PdfTextReader",
    "PinnedModel",
    "PinnedModels",
    "Pipeline",
    "Provenance",
    "Questions",
    "RapidOcrEngine",
    "RegexGenerator",
    "ReplayBatch",
    "ReplayReport",
    "ReviewItem",
    "ReviewQueue",
    "ReviewSink",
    "RobotsDisallowedError",
    "RowRole",
    "RunBudget",
    "RunLedger",
    "SQLiteStore",
    "SchemaConfig",
    "SchemaSpec",
    "SelectStage",
    "SimpleFetcher",
    "SingleEntity",
    "SkippedBlob",
    "Source",
    "Span",
    "SpecScope",
    "SpendEntry",
    "Stage",
    "Statement",
    "StatementKind",
    "StatementStage",
    "Stats",
    "Store",
    "StoreError",
    "StructuredBlob",
    "StructuredMode",
    "StructuredResult",
    "StructuredSource",
    "StructuredStage",
    "TableCell",
    "TableCellRef",
    "TextReader",
    "ToClassify",
    "Tolerance",
    "UnreadableImageError",
    "UnreadablePdfError",
    "UnsupportedDocumentError",
    "ValueStat",
    "VerifiedExample",
    "__version__",
    "blank_rows",
    "book_values",
    "books_corpus",
    "bootstrap_interval",
    "check_baseline",
    "check_lock",
    "community_packs",
    "compile_pack",
    "corpus_digest",
    "cut_statement",
    "default_registry",
    "diff_packs",
    "document_stat",
    "ensure_comparable",
    "evaluate",
    "example_id",
    "example_statement",
    "export_pack",
    "flatten",
    "gate_units",
    "gated_out_pages",
    "generator_record",
    "generator_spec_json_schema",
    "generator_use",
    "header_prefix",
    "import_pack",
    "infer_headers",
    "layered_generators",
    "load_corpus",
    "load_pack",
    "lock_corpus",
    "normalise",
    "open_store",
    "pack_generators",
    "render_page",
    "replay",
    "review_items",
    "row_roles",
    "run_chain",
    "section_text",
    "stats_server",
    "stored_generators",
    "table_statements",
    "text_components",
    "verify_lock",
]
