"""jevex: extract typed records from web pages and PDFs using Jev."""

from jevex._pdfium import UnreadablePdfError
from jevex.budgets import BudgetEvent, Budgets, DocBudget, DocumentBudget, RunBudget, RunLedger
from jevex.categorise import CategoriseStage, JevStatementClassifier, ToClassify
from jevex.clean import BoilerplateCleaner, CleanStage
from jevex.component_gate import ComponentGateStage, GateUnit, NoulComponentGate, gate_units
from jevex.document import Document
from jevex.entities import EntityScope
from jevex.eval import EvalReport, Tolerance, evaluate, load_corpus
from jevex.extractor import ExtractionResult, Extractor
from jevex.fetch import FetchError, RobotsDisallowedError, SimpleFetcher
from jevex.gate import (
    DefaultTextReader,
    DocumentGateStage,
    DocumentText,
    HtmlTextReader,
    NoulDocumentGate,
    PdfTextReader,
    TextReader,
)
from jevex.generators import (
    GeneratorRegistry,
    GeneratorSpec,
    InvalidGeneratorError,
    MatchSpec,
    Provenance,
    RegexGenerator,
    SpecScope,
    default_registry,
    generator_spec_json_schema,
)
from jevex.images import (
    DefaultImageLoader,
    ImageData,
    ImageLoader,
    ImageReading,
    ImageStage,
    ImageText,
    OcrEngine,
    OcrProcessor,
    RapidOcrEngine,
    UnreadableImageError,
    text_components,
)
from jevex.keypaths import (
    FlatBlob,
    KeyPathMapper,
    Leaf,
    StructuredResult,
    StructuredStage,
    flatten,
)
from jevex.layout import (
    BBox,
    Component,
    ComponentType,
    DomLocation,
    ImageLocation,
    LayoutStage,
    Location,
    PageLocation,
    TableCell,
    UnsupportedDocumentError,
    gated_out_pages,
    section_text,
)
from jevex.layout_html import HtmlLayoutParser
from jevex.layout_pdf import DoclingConverter, PdfLayoutError, PdfLayoutParser
from jevex.normalise import (
    BUILTIN_NORMALISERS,
    FunctionNormaliser,
    NormaliseError,
    NormaliserRegistry,
    NormaliseStage,
    normalise,
    run_chain,
)
from jevex.pipeline import Context, Pipeline, Stage
from jevex.resolve import (
    ChildFieldError,
    EntityStage,
    InvalidScopeError,
    MultiEntity,
    ParentChild,
    SingleEntity,
)
from jevex.results import Extracted, FieldMeta, Source
from jevex.schema import Field, FieldSpec, Questions, SchemaConfig, SchemaSpec
from jevex.select import CandidateStage, JevCandidateSelector, SelectStage
from jevex.split import DefaultSplitter, DuplicateStatementError, StatementStage, cut_statement
from jevex.statements import (
    Candidate,
    NormaliserStep,
    Span,
    Statement,
    StatementKind,
    TableCellRef,
)
from jevex.store import (
    GeneratorRecord,
    GeneratorStats,
    KeyMapping,
    SpendEntry,
    SQLiteStore,
    Store,
    StoreError,
    VerifiedExample,
    open_store,
)
from jevex.structured import (
    EmbeddedData,
    EmbeddedDataReader,
    SkippedBlob,
    StructuredBlob,
    StructuredSource,
)
from jevex.tables import blank_rows, header_prefix, table_statements

__version__ = "0.0.1"

__all__ = [
    "BUILTIN_NORMALISERS",
    "BBox",
    "BoilerplateCleaner",
    "BudgetEvent",
    "Budgets",
    "Candidate",
    "CandidateStage",
    "CategoriseStage",
    "ChildFieldError",
    "CleanStage",
    "Component",
    "ComponentGateStage",
    "ComponentType",
    "Context",
    "DefaultImageLoader",
    "DefaultSplitter",
    "DefaultTextReader",
    "DocBudget",
    "DoclingConverter",
    "Document",
    "DocumentBudget",
    "DocumentGateStage",
    "DocumentText",
    "DomLocation",
    "DuplicateStatementError",
    "EmbeddedData",
    "EmbeddedDataReader",
    "EntityScope",
    "EntityStage",
    "EvalReport",
    "Extracted",
    "ExtractionResult",
    "Extractor",
    "FetchError",
    "Field",
    "FieldMeta",
    "FieldSpec",
    "FlatBlob",
    "FunctionNormaliser",
    "GateUnit",
    "GeneratorRecord",
    "GeneratorRegistry",
    "GeneratorSpec",
    "GeneratorStats",
    "HtmlLayoutParser",
    "HtmlTextReader",
    "ImageData",
    "ImageLoader",
    "ImageLocation",
    "ImageReading",
    "ImageStage",
    "ImageText",
    "InvalidGeneratorError",
    "InvalidScopeError",
    "JevCandidateSelector",
    "JevStatementClassifier",
    "KeyMapping",
    "KeyPathMapper",
    "LayoutStage",
    "Leaf",
    "Location",
    "MatchSpec",
    "MultiEntity",
    "NormaliseError",
    "NormaliseStage",
    "NormaliserRegistry",
    "NormaliserStep",
    "NoulComponentGate",
    "NoulDocumentGate",
    "OcrEngine",
    "OcrProcessor",
    "PageLocation",
    "ParentChild",
    "PdfLayoutError",
    "PdfLayoutParser",
    "PdfTextReader",
    "Pipeline",
    "Provenance",
    "Questions",
    "RapidOcrEngine",
    "RegexGenerator",
    "RobotsDisallowedError",
    "RunBudget",
    "RunLedger",
    "SQLiteStore",
    "SchemaConfig",
    "SchemaSpec",
    "SelectStage",
    "SimpleFetcher",
    "SingleEntity",
    "SkippedBlob",
    "Source",
    "Span",
    "SpecScope",
    "SpendEntry",
    "Stage",
    "Statement",
    "StatementKind",
    "StatementStage",
    "Store",
    "StoreError",
    "StructuredBlob",
    "StructuredResult",
    "StructuredSource",
    "StructuredStage",
    "TableCell",
    "TableCellRef",
    "TextReader",
    "ToClassify",
    "Tolerance",
    "UnreadableImageError",
    "UnreadablePdfError",
    "UnsupportedDocumentError",
    "VerifiedExample",
    "__version__",
    "blank_rows",
    "cut_statement",
    "default_registry",
    "evaluate",
    "flatten",
    "gate_units",
    "gated_out_pages",
    "generator_spec_json_schema",
    "header_prefix",
    "load_corpus",
    "normalise",
    "open_store",
    "run_chain",
    "section_text",
    "table_statements",
    "text_components",
]
